const { Schema, model } = require('mongoose');

const oldSpeciesSchema = new Schema({
  id: { type: Number, required: true, unique: true },
  year: Number,
  bibliography: String,
  author: { type: String, maxLength: 255 },
  scientific_name: { type: String, maxLength: 255 },
  status: { type: String, maxLength: 255 },
  plant_id: { type: Number },
  plant_objId: { type: Schema.Types.ObjectId, ref: "plant" },
  slug: { type: String, maxLength: 255 },
  inserted_at: { type: Date, default: Date.now },
  updated_at: { type: Date, default: Date.now },
  fruit_conspicuous: Boolean,
  coppice_potential: Boolean,
  fruit_seed_period_end: { type: String, maxLength: 255 },
  resprout_ability: Boolean,
  propagated_by_sprigs: Boolean,
  propagated_by_cuttings: Boolean,
  fodder_product: Boolean,
  precipitation_minimum: Number,
  toxicity: { type: String, maxLength: 255 },
  foliage_texture: { type: String, maxLength: 255 },
  fruit_seed_abundance: { type: String, maxLength: 255 },
  fire_resistance: Boolean,
  height_at_base_age_max_ft: Number,
  fall_conspicuous: Boolean,
  fire_tolerance: { type: String, maxLength: 255 },
  ph_minimum: Number,
  propagated_by_container: Boolean,
  flower_conspicuous: Boolean,
  native_status: { type: String, maxLength: 255 },
  fuelwood_product: { type: String, maxLength: 255 },
  frost_free_days_minimum: Number,
  growth_habit: { type: String, maxLength: 255 },
  protein_potential: { type: String, maxLength: 255 },
  planting_density_per_acre_maximum: Number,
  root_depth_minimum_inches: Number,
  adapted_to_medium_textured_soils: Boolean,
  growth_form: { type: String, maxLength: 255 },
  after_harvest_regrowth_rate: { type: String, maxLength: 255 },
  drought_tolerance: { type: String, maxLength: 255 },
  salinity_tolerance: { type: String, maxLength: 255 },
  fertility_requirement: { type: String, maxLength: 255 },
  foliage_color: { type: String, maxLength: 255 },
  nitrogen_fixation: { type: String, maxLength: 255 },
  commercial_availability: { type: String, maxLength: 255 },
  anaerobic_tolerance: { type: String, maxLength: 255 },
  lifespan: { type: String, maxLength: 255 },
  veneer_product: Boolean,
  bloat: { type: String, maxLength: 255 },
  precipitation_maximum: Number,
  planting_density_per_acre_minimum: Number,
  foliage_porosity_winter: { type: String, maxLength: 255 },
  height_mature_ft: Number,
  ph_maximum: Number,
  christmas_tree_product: Boolean,
  shape_and_orientation: { type: String, maxLength: 255 },
  shade_tolerance: { type: String, maxLength: 255 },
  usda_synonym: { type: String, maxLength: 255 },
  pulpwood_product: Boolean,
  small_grain: Boolean,
  low_growing_grass: Boolean,
  berry_nut_seed_product: Boolean,
  vegetative_spread_rate: { type: String, maxLength: 255 },
  propagated_by_bare_root: Boolean,
  propagated_by_sod: Boolean,
  fruit_seed_period_begin: { type: String, maxLength: 255 },
  palatable_browse_animal: { type: String, maxLength: 255 },
  foliage_porosity_summer: { type: String, maxLength: 255 },
  seeds_per_pound: Number,
  adapted_to_fine_textured_soils: Boolean,
  hedge_tolerance: { type: String, maxLength: 255 },
  post_product: Boolean,
  growth_rate: { type: String, maxLength: 255 },
  propagated_by_seed: Boolean,
  fruit_color: { type: String, maxLength: 255 },
  nursery_stock_product: Boolean,
  seedling_vigor: { type: String, maxLength: 255 },
  cold_stratification_required: Boolean,
  palatable_graze_animal: { type: String, maxLength: 255 },
  bloom_period: { type: String, maxLength: 255 },
  fruit_seed_persistence: Boolean,
  propagated_by_bulbs: Boolean,
  active_growth_period: { type: String, maxLength: 255 },
  c_n_ratio: { type: String, maxLength: 255 },
  duration: { type: String, maxLength: 255 },
  flower_color: { type: String, maxLength: 255 },
  leaf_retention: Boolean,
  known_allelopath: Boolean,
  palatable_human: Boolean,
  propagated_by_tubers: Boolean,
  moisture_use: { type: String, maxLength: 255 },
  lumber_product: Boolean,
  adapted_to_coarse_textured_soils: Boolean,
  propagated_by_corms: Boolean,
  temperature_minimum_deg_f: Number,
  naval_store_product: Boolean,
  seed_spread_rate: { type: String, maxLength: 255 },
  caco_3_tolerance: { type: String, maxLength: 255 },
  species_type: { type: String, maxLength: 255 },
  genus_id: { type: Number },
  genus_objId: { type: Schema.Types.ObjectId, ref: "genus" },
  main_species_id: { type: Number },
  main_species_objId: { type: Schema.Types.ObjectId, ref: "species" },
  usda_name: { type: String, maxLength: 255 },
  family_common_name: { type: String, maxLength: 255 },
  common_name: { type: String, maxLength: 255 },
  complete_data: Boolean,
  synonym_of_id: Number,
  synonym_of_objId: { type: Schema.Types.ObjectId, ref: "synonym" },
  observations: String,
  vegetable: Boolean,
  edible: Boolean,
  reviewed_at: { type: Date, default: Date.now },
  created_at: { type: Date, default: Date.now },
  average_mature_height_value: Number,
  average_mature_height_unit: { type: String, maxLength: 12 },
  maximum_height_value: Number,
  maximum_height_unit: { type: String, maxLength: 12 },
  minimum_root_depth_value: Number,
  minimum_root_depth_unit: { type: String, maxLength: 12 },
  minimum_planting_density_value: Number,
  minimum_planting_density_unit: { type: String, maxLength: 12 },
  minimum_precipitation_value: Number,
  minimum_precipitation_unit: { type: String, maxLength: 12 },
  maximum_precipitation_value: Number,
  maximum_precipitation_unit: { type: String, maxLength: 12 },
  minimum_temperature_deg_f: Number,
  minimum_temperature_deg_c: Number,
  maximum_temperature_deg_f: Number,
  maximum_temperature_deg_c: Number,
  rank: Number,
  sources_count: Number,
  images_count: Number,
  synonyms_count: Number,
  gbif_score: Number,
  duration_fl: Number,
  propagated_by: Number,
  growth_months: Number,
  bloom_months: Number,
  fruit_months: Number,
});

const OldSpeciesModel = model("old_species", oldSpeciesSchema);

module.exports = OldSpeciesModel;