const { Schema, model } = require('mongoose');

const speciesSchema = new Schema({
  id: { type: Number, required: true, unique: true },
  year: Number,
  bibliography: String,
  author: { type: String, maxLength: 255 },
  scientific_name: { type: String, maxLength: 255, unique: true },
  plant_id: { type: Number },
  plant_objId: { type: Schema.Types.ObjectId, ref: "plant" },
  inserted_at: { type: Date, default: Date.now, required: true },
  updated_at: { type: Date, default: Date.now, required: true },
  fruit_conspicuous: Boolean,
  ph_minimum: Number,
  flower_conspicuous: Boolean,
  frost_free_days_minimum: Number,
  growth_habit: { type: String, maxLength: 255 },
  protein_potential: { type: String, maxLength: 255 },
  adapted_to_medium_textured_soils: Boolean,
  growth_form: { type: String, maxLength: 255 },
  nitrogen_fixation: { type: String, maxLength: 255 },
  anaerobic_tolerance: { type: String, maxLength: 255 },
  lifespan: { type: String, maxLength: 255 },
  ph_maximum: Number,
  shape_and_orientation: { type: String, maxLength: 255 },
  adapted_to_fine_textured_soils: Boolean,
  growth_rate: { type: String, maxLength: 255 },
  fruit_seed_persistence: Boolean,
  c_n_ratio: { type: String, maxLength: 255 },
  leaf_retention: Boolean,
  known_allelopath: Boolean,
  adapted_to_coarse_textured_soils: Boolean,
  caco_3_toleranceo: { type: String, maxLength: 255 },
  genus_id: { type: Number },
  genus_objId: { type: Schema.Types.ObjectId, ref: "genus" },
  main_species_id: { type: Number },
  main_species_objId: { type: Schema.Types.ObjectId, ref: "species" },
  family_common_name: { type: String, maxLength: 255 },
  common_name: { type: String, maxLength: 255 },
  complete_data: Boolean,
  observations: String,
  vegetable: Boolean,
  edible: Boolean,
  reviewed_at: { type: Date, default: Date.now },
  created_at: { type: Date, default: Date.now },
  minimum_temperature_deg_f: Number,
  minimum_temperature_deg_c: Number,
  maximum_temperature_deg_f: Number,
  maximum_temperature_deg_c: Number,
  rank: String,
  sources_count: { type: Number, default: 0, required: true },
  images_count: { type: Number, default: 0, required: true },
  synonyms_count: { type: Number, default: 0, required: true },
  gbif_score: { type: Number, default: 0, required: true },
  duration: { type: Number, default: 0, required: true },
  propagated_by: { type: Number, default: 0, required: true },
  growth_months: { type: Number, default: 0, required: true },
  bloom_months: { type: Number, default: 0, required: true },
  fruit_months: { type: Number, default: 0, required: true },
  status: String,
  toxicity: String,
  foliage_texture: String,
  inflorescence_raw: String,
  sexuality_raw: String,
  maturation_order: String,
  pollinisation_raw: String,
  fruit_shape_raw: String,
  dissemination_raw: String,
  ligneous_type: String,
  flower_color: { type: Number, default: 0, required: true },
  fruit_color: { type: Number, default: 0, required: true },
  light: Number,
  atmospheric_humidity: Number,
  ground_humidity: Number,
  foliage_color: { type: Number, default: 0, required: true },
  soil_texture: String,
  soil_salinity: Number,
  soil_nutriments: Number,
  hardiness_zone: Number,
  inflorescence_form: Number,
  inflorescence_type: Number,
  sexuality: { type: Number, default: 0, required: true },
  maturation_order_raw: String,
  pollinisation: { type: Number, default: 0, required: true },
  fruit_shape: Number,
  dissemination: { type: Number, default: 0, required: true },
  biological_type: Number,
  biological_type_raw: String,
  checked_at: { type: Date, default: Date.now },
  token: String,
  full_token: String,
  edible_part: { type: Number, default: 0, required: true },
  planting_description: String,
  planting_sowing_description: String,
  planting_days_to_harvest: Number,
  planting_row_spacing_cm: Number,
  planting_spread_cm: Number,
  main_image_url: String,
  maximum_height_cm: Number,
  maximum_precipitation_mm: Number,
  minimum_precipitation_mm: Number,
  minimum_root_depth_cm: Number,
  genus_name: String,
  family_name: String,
  average_height_cm: Number,
  completion_ratio: Number,
  phylum: String,
  wiki_score: Number
});

const SpeciesModel = model("species", speciesSchema);

module.exports = SpeciesModel;